# Generated by Django 3.2.16 on 2024-04-21 22:24

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20240421_2341'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('user', django.db.models.expressions.F('following')), _negated=True), name='following'),
        ),
    ]
